
server:
  port: 5056
  servlet:
    context-path: /api/v1/inventory

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: ${SAMPLEAPP_DB}
      database: Cluster0
  rabbitmq:
    virtual-host: ewpqkngf
    host: cow-01.rmq2.cloudamqp.com
    password: ${SAMPLEAPP_RMQ_PWD}
    port: 5672
    username: ewpqkngf

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5052/eureka