
spring:
  application:
    name:
      discovery-server

server:
  port:
    5052
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:5052/eureka